### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by djmattyg007** [jez/barchart#3]
I wanted to let you know that I've created an AUR package for this tool, in case you wanted to add a note to the readme or something like that.

https://aur.archlinux.org/packages/barchart/

**Comment by jez** [comment]
Thanks for the heads up. I don't link to things in my READMEs that I don't maintain (because then when they're out of date, people ask me to update them and I can't).

Glad you found a use for the project and put the work into making it easier to use on your preferred platform.
